1.0.50

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -67,12 +67,21 @@ jobs:
             echo "Deploying new application..."
             mkdir -p /home/ubuntu/cpu/  # 필요한 경우, 배포 디렉토리 생성
             mv ./build/libs/web-0.0.1-SNAPSHOT.jar /home/ubuntu/cpu/web-0.0.1-SNAPSHOT.jar  # JAR 파일 이동
+            if [ -f "/home/ubuntu/cpu/web-0.0.1-SNAPSHOT.jar" ]; then
+              echo "JAR file moved successfully."
+            else
+              echo "Failed to move JAR file."
+              exit 1  # JAR 파일 이동에 실패하면 스크립트를 종료합니다.
+            fi
+
             nohup java -jar /home/ubuntu/cpu/web-0.0.1-SNAPSHOT.jar > /home/ubuntu/cpu/app.log 2>&1 &  # 새 JAR 파일로 애플리케이션 실행 및 로그 저장
             NEW_PID=$(pgrep -f 'java -jar')
             if [ -n "$NEW_PID" ]; then
               echo "New application started with PID $NEW_PID"
             else
               echo "Failed to start new application"
+              tail -n 50 /home/ubuntu/cpu/app.log  # 애플리케이션 로그의 마지막 50줄을 출력하여 문제를 파악합니다.
+              exit 1  # 애플리케이션 시작에 실패하면 스크립트를 종료합니다.
             fi  
           EOF
 
